name: Generate assets

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "*/10 * * * *"

jobs:
  github-contributions-snake:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: assets
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: fregante/setup-git-user@v2

      - uses: Platane/snk/svg-only@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-snake.svg?palette=github-dark

      - name: Squash and Commit
        run: |
          git add .
          git reset --soft HEAD~2
          git push -f 